# Generated by Django 6.0.4 on 2026-05-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('summary', models.CharField(help_text='One-sentence summary shown on cards and the home page.', max_length=200)),
                ('category', models.CharField(choices=[('AI', 'Artificial Intelligence'), ('ML', 'Machine Learning'), ('AUTO', 'Automation / Agents'), ('WEB', 'Web Development'), ('MEDIA', 'Generative Media')], default='AI', max_length=10)),
                ('business_problem', models.TextField(help_text='What real-world problem does this project solve?')),
                ('tools_used', models.CharField(help_text="Comma-separated list, e.g. 'Python, Django, LangChain, OpenAI API'", max_length=300)),
                ('key_features', models.TextField(help_text='One feature per line. Rendered as a bulleted list.')),
                ('role_contribution', models.TextField(help_text='Your specific role and what you personally built.')),
                ('biggest_challenge', models.TextField(help_text='The hardest technical or design problem you solved.')),
                ('lessons_learned', models.TextField(help_text='Key takeaways an interviewer would want to hear.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('link', models.URLField(blank=True, help_text='GitHub repo, live demo, or video walkthrough URL.')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on the home page hero section.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers display first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
