# Generated by Django 6.0.4 on 2026-05-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deliverable_file',
            field=models.FileField(blank=True, help_text='Optional: a downloadable deliverable (PDF, PPTX, ZIP, etc.) shown as a download button.', null=True, upload_to='deliverables/'),
        ),
        migrations.AddField(
            model_name='project',
            name='deliverable_label',
            field=models.CharField(blank=True, default='Download Deliverable', help_text="Optional: text shown on the download button (e.g., 'Download Pitch Deck', 'Download Resume', 'Download Workflow JSON').", max_length=60),
        ),
        migrations.AddField(
            model_name='project',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional: YouTube embed URL (use the URL from Share → Embed, format https://www.youtube.com/embed/VIDEO_ID).'),
        ),
    ]
